const express = require("express"),
  morgan = require("morgan"),
  fs = require("fs"),
  path = require("path"),
  bodyParser = require("body-parser"),
  methodOverride = require("method-override");

const app = express();
app.use(morgan("common"));
// Create a write stream (in append mode) a ‘log.txt’ file is created in root directory
const accessLogStream = fs.createWriteStream(path.join(__dirname, "log.txt"), {
  flags: "a",
});

// Setup the logger
app.use(morgan("combined", { stream: accessLogStream }));

app.use(
  bodyParser.urlencoded({
    extended: true,
  })
);

app.use(bodyParser.json());
app.use(methodOverride());
// In-Memory Details from imdb generated by chatGPT for my top ten (https://chat.openai.com/share/8cfa20d9-69e9-42e2-93f5-fde520de0563)
let myTopTen = {
  "Forrest Gump": {
    Title: "Forrest Gump",
    Year: "1994",
    Rated: "PG-13",
    Released: "06 Jul 1994",
    Runtime: "142 min",
    Genre: "Drama, Romance",
    Director: "Robert Zemeckis",
    Writer: "Winston Groom (novel), Eric Roth (screenplay)",
    Actors:
      "Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys",
    Plot: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    Language: "English",
    Country: "USA",
    Awards: "Won 6 Oscars. Another 44 wins & 76 nominations.",
    imdbRating: "8.8",
    imdbVotes: "1,895,641",
    imdbID: "tt0109830",
    Type: "movie",
    DVD: "28 Aug 2001",
    BoxOffice: "N/A",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  "Remember the Titans": {
    Title: "Remember the Titans",
    Year: "2000",
    Rated: "PG",
    Released: "29 Sep 2000",
    Runtime: "113 min",
    Genre: "Biography, Drama, Sport",
    Director: "Boaz Yakin",
    Writer: "Gregory Allen Howard",
    Actors: "Denzel Washington, Will Patton, Wood Harris, Ryan Hurst",
    Plot: "The true story of a newly appointed African-American coach and his high school team on their first season as a racially integrated unit.",
    Language: "English",
    Country: "USA",
    Awards: "9 wins & 13 nominations.",
    imdbRating: "7.8",
    imdbVotes: "232,841",
    imdbID: "tt0210945",
    Type: "movie",
    DVD: "20 Mar 2001",
    BoxOffice: "$115,648,585",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  "Captain Ron": {
    Title: "Captain Ron",
    Year: "1992",
    Rated: "PG-13",
    Released: "18 Sep 1992",
    Runtime: "90 min",
    Genre: "Adventure, Comedy",
    Director: "Thom Eberhardt",
    Writer: "John Dwyer",
    Actors: "Kurt Russell, Martin Short, Mary Kay Place, Benjamin Salisbury",
    Plot: "A family in Chicago inherits the yacht formerly owned by Clark Gable. They decide to sail it from the island of Ste. Pomme de Terre to Miami, and they sail with the assistance of Captain Ron and their lives will never be the same again.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    imdbRating: "5.7",
    imdbVotes: "21,156",
    imdbID: "tt0103924",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "Touchstone Pictures",
    Website: "N/A",
    Response: "True",
  },
  "A League of Their Own": {
    Title: "A League of Their Own",
    Year: "1992",
    Rated: "PG",
    Released: "01 Jul 1992",
    Runtime: "128 min",
    Genre: "Comedy, Drama, Sport",
    Director: "Penny Marshall",
    Writer:
      "Kim Wilson (story), Kelly Candaele (story), Kim Wilson (screenplay), Kelly Candaele (screenplay)",
    Actors: "Tom Hanks, Geena Davis, Madonna, Lori Petty",
    Plot: "Two sisters join the first female professional baseball league and struggle to help it succeed amidst their own growing rivalry.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 2 Golden Globes. Another 8 wins & 9 nominations.",
    imdbRating: "7.3",
    imdbVotes: "98,003",
    imdbID: "tt0104694",
    Type: "movie",
    DVD: "25 Apr 2000",
    BoxOffice: "N/A",
    Production: "Columbia Pictures",
    Website: "N/A",
    Response: "True",
  },
  Armageddon: {
    Title: "Armageddon",
    Year: "1998",
    Rated: "PG-13",
    Released: "01 Jul 1998",
    Runtime: "151 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Michael Bay",
    Writer:
      "Jonathan Hensleigh (screenplay), J.J. Abrams (screenplay), Tony Gilroy (adaptation), Shane Salerno (adaptation), Robert Roy Pool (story), Jonathan Hensleigh (story)",
    Actors: "Bruce Willis, Billy Bob Thornton, Ben Affleck, Liv Tyler",
    Plot: "After discovering that an asteroid the size of Texas is going to impact Earth in less than a month, NASA recruits a misfit team of deep-core drillers to save the planet.",
    Language: "English, Russian, Indonesian",
    Country: "USA",
    Awards: "Nominated for 4 Oscars. Another 15 wins & 36 nominations.",
    imdbRating: "6.7",
    imdbVotes: "410,052",
    imdbID: "tt0120591",
    Type: "movie",
    DVD: "19 Jan 1999",
    BoxOffice: "$201,573,391",
    Production: "Touchstone Pictures",
    Website: "N/A",
    Response: "True",
  },
  "Last Holiday": {
    Title: "Last Holiday",
    Year: "2006",
    Rated: "PG-13",
    Released: "13 Jan 2006",
    Runtime: "112 min",
    Genre: "Comedy, Drama",
    Director: "Wayne Wang",
    Writer:
      "Jeffrey Price (screenplay), Peter S. Seaman (screenplay), J.B. Priestley (based upon the motion picture screenplay by)",
    Actors: "Queen Latifah, LL Cool J, Timothy Hutton, Giancarlo Esposito",
    Plot: "Upon learning of a terminal illness, a shy woman decides to sell off all her possessions and live it up at a posh European hotel.",
    Language: "English",
    Country: "USA",
    Awards: "1 win & 5 nominations.",
    imdbRating: "6.4",
    imdbVotes: "44,301",
    imdbID: "tt0408985",
    Type: "movie",
    DVD: "18 Apr 2006",
    BoxOffice: "$38,399,961",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  "Inside Out": {
    Title: "Inside Out",
    Year: "2015",
    Rated: "PG",
    Released: "19 Jun 2015",
    Runtime: "95 min",
    Genre: "Animation, Adventure, Comedy, Drama, Family, Fantasy",
    Director: "Pete Docter, Ronnie Del Carmen(co-director)",
    Writer:
      "Pete Docter (original story by), Ronnie Del Carmen (original story by), Pete Docter (screenplay by), Meg LeFauve (screenplay by), Josh Cooley (screenplay by), Michael Arndt (additional story material by), Simon Rich (additional story material by), Bill Hader (additional dialogue by), Amy Poehler (additional dialogue by)",
    Actors: "Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader",
    Plot: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
    Language: "English",
    Country: "USA",
    Awards: "Won 1 Oscar. Another 98 wins & 117 nominations.",
    imdbRating: "8.1",
    imdbVotes: "649,109",
    imdbID: "tt2096673",
    Type: "movie",
    DVD: "03 Nov 2015",
    BoxOffice: "$356,461,711",
    Production: "Walt Disney Pictures",
    Website: "N/A",
    Response: "True",
  },
  Hitch: {
    Title: "Hitch",
    Year: "2005",
    Rated: "PG-13",
    Released: "11 Feb 2005",
    Runtime: "118 min",
    Genre: "Comedy, Romance",
    Director: "Andy Tennant",
    Writer: "Kevin Bisch",
    Actors: "Will Smith, Eva Mendes, Kevin James, Amber Valletta",
    Plot: "While helping his latest client woo the woman of his dreams, a professional date-doctor finds that his game doesn't quite work on the gossip columnist with whom he's smitten.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "4 wins & 24 nominations.",
    imdbRating: "6.6",
    imdbVotes: "301,857",
    imdbID: "tt0386588",
    Type: "movie",
    DVD: "28 Jun 2005",
    BoxOffice: "$179,495,555",
    Production: "Sony Pictures",
    Website: "N/A",
    Response: "True",
  },
  "13 Hours": {
    Title: "13 Hours",
    Year: "2016",
    Rated: "R",
    Released: "15 Jan 2016",
    Runtime: "144 min",
    Genre: "Action, Drama, History, Thriller, War",
    Director: "Michael Bay",
    Writer: "Chuck Hogan (screenplay), Mitchell Zuckoff (book)",
    Actors: "John Krasinski, James Badge Dale, Pablo Schreiber, David Denman",
    Plot: "During an attack on a U.S. compound in Libya, a security team struggles to make sense out of the chaos.",
    Language: "English, Arabic",
    Country: "USA, Malta, Morocco",
    Awards: "2 nominations.",
    imdbRating: "7.3",
    imdbVotes: "86,580",
    imdbID: "tt4172430",
    Type: "movie",
    DVD: "07 Jun 2016",
    BoxOffice: "$52,853,219",
    Production: "Paramount Pictures",
    Website: "N/A",
    Response: "True",
  },
  "Sydney White": {
    Title: "Sydney White",
    Year: "2007",
    Rated: "PG-13",
    Released: "21 Sep 2007",
    Runtime: "108 min",
    Genre: "Comedy, Drama, Romance",
    Director: "Joe Nussbaum",
    Writer:
      "Chad Gomez Creasey (screenplay), Chad Gomez Creasey (story), Dara Resnik Creasey (screenplay)",
    Actors: "Amanda Bynes, Sara Paxton, Matt Long, Jack Carpenter",
    Plot: "A modern retelling of Snow White set against students in their freshman year of college in the greek system.",
    Language: "English",
    Country: "USA, Canada",
    Awards: "N/A",
    imdbRating: "6.2",
    imdbVotes: "40,455",
    imdbID: "tt0815244",
    Type: "movie",
    DVD: "22 Jan 2008",
    BoxOffice: "$11,892,415",
    Production: "Morgan Creek Entertainment",
    Website: "N/A",
    Response: "True",
  },
};

// In-Memory Details from imdb generated by chatGPT for genres and their details (https://chat.openai.com/share/9592f50a-62c7-454e-b640-029daf603b2c)
let genres = {
  Action: {
    description:
      "Movies characterized by exciting sequences, fast-paced action, and often featuring heroic protagonists.",
    example_movies: ["Die Hard", "Mad Max: Fury Road", "The Dark Knight"],
  },
  Comedy: {
    description:
      "Movies intended to make the audience laugh, often featuring humorous situations, witty dialogue, and comedic performances.",
    example_movies: [
      "Superbad",
      "The Hangover",
      "Anchorman: The Legend of Ron Burgundy",
    ],
  },
  Drama: {
    description:
      "Movies focused on realistic characters and emotional themes, often exploring complex human relationships and societal issues.",
    example_movies: [
      "The Shawshank Redemption",
      "Forrest Gump",
      "The Godfather",
    ],
  },
  Horror: {
    description:
      "Movies designed to evoke fear, suspense, and terror in the audience, often featuring supernatural elements, monsters, or psychological horror.",
    example_movies: ["The Shining", "Get Out", "A Nightmare on Elm Street"],
  },
  "Science Fiction": {
    description:
      "Movies that explore speculative or futuristic concepts, often involving advanced technology, space exploration, or extraterrestrial life.",
    example_movies: ["Star Wars", "Blade Runner", "The Matrix"],
  },
  Fantasy: {
    description:
      "Movies set in imaginary worlds with fantastical elements such as magic, mythical creatures, and epic quests.",
    example_movies: [
      "The Lord of the Rings",
      "Harry Potter",
      "Pan's Labyrinth",
    ],
  },
  Thriller: {
    description:
      "Movies characterized by intense excitement, suspense, and anticipation, often featuring plot twists and high stakes.",
    example_movies: ["The Silence of the Lambs", "Inception", "Se7en"],
  },
  Romance: {
    description:
      "Movies centered around romantic relationships, love, and affection, often featuring emotional connections and heartwarming moments.",
    example_movies: ["Titanic", "The Notebook", "Pride and Prejudice"],
  },
  Adventure: {
    description:
      "Movies focused on exciting journeys, exploration, and discovery, often set in exotic or dangerous locations.",
    example_movies: [
      "Indiana Jones and the Raiders of the Lost Ark",
      "Jurassic Park",
      "The Goonies",
    ],
  },
  Animation: {
    description:
      "Movies created using animation techniques, including traditional hand-drawn animation, computer-generated imagery (CGI), and stop-motion animation.",
    example_movies: ["Toy Story", "Spirited Away", "The Lion King"],
  },
};

// In-Memory Details from imdb generated by chatGPT for directors and their details ((https://chat.openai.com/share/8cfa20d9-69e9-42e2-93f5-fde520de0563)
let directors = {
  "Christopher Nolan": {
    "Full Name": "Christopher Edward Nolan",
    "Date of Birth": "July 30, 1970",
    Birthplace: "London, England, UK",
    "Known For": ["The Dark Knight Trilogy", "Inception", "Interstellar"],
    Awards: [
      "Academy Award nominations for Best Director and Best Picture for Inception and Dunkirk",
    ],
    "IMDb Profile": "https://www.imdb.com/name/nm0634240/",
  },
  "Steven Spielberg": {
    "Full Name": "Steven Allan Spielberg",
    "Date of Birth": "December 18, 1946",
    Birthplace: "Cincinnati, Ohio, USA",
    "Known For": ["Jaws", "E.T. the Extra-Terrestrial", "Schindler's List"],
    Awards: [
      "Multiple Academy Awards including Best Director for Schindler's List and Saving Private Ryan",
    ],
    "IMDb Profile": "https://www.imdb.com/name/nm0000229/",
  },
  "Quentin Tarantino": {
    "Full Name": "Quentin Jerome Tarantino",
    "Date of Birth": "March 27, 1963",
    Birthplace: "Knoxville, Tennessee, USA",
    "Known For": ["Pulp Fiction", "Kill Bill", "Django Unchained"],
    Awards: [
      "Academy Awards for Best Original Screenplay for Pulp Fiction and Django Unchained",
    ],
    "IMDb Profile": "https://www.imdb.com/name/nm0000233/",
  },
  "Martin Scorsese": {
    "Full Name": "Martin Charles Scorsese",
    "Date of Birth": "November 17, 1942",
    Birthplace: "Queens, New York City, New York, USA",
    "Known For": ["Goodfellas", "Taxi Driver", "The Departed"],
    Awards: ["Academy Awards for Best Director for The Departed"],
    "IMDb Profile": "https://www.imdb.com/name/nm0000217/",
  },
  "Stanley Kubrick": {
    "Full Name": "Stanley Kubrick",
    "Date of Birth": "July 26, 1928",
    Birthplace: "New York City, New York, USA",
    "Known For": ["2001: A Space Odyssey", "A Clockwork Orange", "The Shining"],
    Awards: ["Academy Award for Best Visual Effects for 2001: A Space Odyssey"],
    "IMDb Profile": "https://www.imdb.com/name/nm0000040/",
  },
};

// In-Memory Details from imdb generated by chatGPT for actors and their details ((https://chat.openai.com/share/8cfa20d9-69e9-42e2-93f5-fde520de0563)
let actorsMovies = {
  "Bruce Willis": {
    Movies: [
      "Die Hard",
      "Pulp Fiction",
      "The Sixth Sense",
      "The Fifth Element",
      "12 Monkeys",
      "Armageddon",
      "Unbreakable",
      "Sin City",
      "Looper",
      "Red",
    ],
  },
  "Billy Bob Thornton": {
    Movies: [
      "Sling Blade",
      "Fargo",
      "Monster's Ball",
      "A Simple Plan",
      "Bad Santa",
      "The Man Who Wasn't There",
      "Armageddon",
      "Pushing Tin",
      "Friday Night Lights",
      "The Astronaut Farmer",
    ],
  },
  "Ben Affleck": {
    Movies: [
      "Good Will Hunting",
      "Argo",
      "Gone Girl",
      "The Town",
      "Pearl Harbor",
      "Shakespeare in Love",
      "Armageddon",
      "Daredevil",
      "Chasing Amy",
      "The Accountant",
    ],
  },
  "Liv Tyler": {
    Movies: [
      "The Lord of the Rings: The Fellowship of the Ring",
      "Armageddon",
      "The Strangers",
      "The Lord of the Rings: The Return of the King",
      "The Lord of the Rings: The Two Towers",
      "That Thing You Do!",
      "Stealing Beauty",
      "Jersey Girl",
      "Empire Records",
      "Inventing the Abbotts",
    ],
  },
};

app.use(express.static("public"));

app.get("/movies", (req, res) => {
  res.json(myTopTen);
});

app.get("/", (req, res) => {
  res.send("Welcome to myFlix!");
});

//   Error handler
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).send("Something broke!");
});

app.listen(8080, () => {
  console.log("Your app is listening on port 8080.");
});

//   CREDITS
//   "Top 100 IMDB Movies" (imdb_data_100.json) by Helena Oliveira, Observable License: [License Type]. Available at: [https://observablehq.com/@btwhelena/top-100-imdb-movies]
